version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14.5-alpine3.16
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
