# Generated by Django 4.1.2 on 2022-10-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(default='/companies/<built-in function id>', max_length=100)),
                ('summary', models.TextField()),
                ('advocates', models.ManyToManyField(blank=True, related_name='companies', to='advocates.advocate')),
            ],
        ),
    ]
