# Generated by Django 4.1.2 on 2022-10-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0002_advocate_company'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='advocates',
            field=models.ManyToManyField(blank=True, related_name='advocate_id', to='advocates.advocate'),
        ),
    ]
