# Generated by Django 4.1.2 on 2022-10-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0007_alter_advocate_companies'),
        ('companies', '0003_alter_company_advocates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='advocates',
            field=models.ManyToManyField(related_name='advocates', to='advocates.advocate'),
        ),
    ]
