# Generated by Django 4.1.2 on 2022-10-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0008_remove_advocate_companies'),
        ('companies', '0004_alter_company_advocates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='advocates',
        ),
        migrations.AddField(
            model_name='company',
            name='advocates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advocates', to='advocates.advocate'),
        ),
    ]
