# Generated by Django 4.1.2 on 2022-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_advocates_company_advocates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='href',
            field=models.CharField(default='/companies/', max_length=100),
        ),
    ]
