# Generated by Django 4.1.2 on 2022-10-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_bio', models.CharField(max_length=100)),
                ('long_bio', models.TextField()),
                ('years_of_experience', models.IntegerField()),
            ],
        ),
    ]
