# Generated by Django 4.1.2 on 2022-10-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='company',
            field=models.ManyToManyField(related_name='company_id', to='companies.company'),
        ),
    ]
