# Generated by Django 4.1.2 on 2022-10-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0002_advocate_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='company',
        ),
    ]
