# Generated by Django 4.1.2 on 2022-10-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_advocates'),
        ('advocates', '0006_advocate_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='companies',
            field=models.ManyToManyField(related_name='companies', to='companies.company'),
        ),
    ]
