# Generated by Django 4.1.2 on 2022-10-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0007_alter_advocate_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='companies',
        ),
    ]
