# Generated by Django 4.1.2 on 2022-10-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_href'),
        ('advocates', '0008_remove_advocate_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='companies.company'),
        ),
    ]
