# Generated by Django 4.1.2 on 2022-10-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0010_remove_advocate_companies_advocate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
