# Generated by Django 4.1.2 on 2022-10-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0014_alter_advocate_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='company',
            new_name='compani',
        ),
    ]
